[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "HideCurrentPlanetInfo"
description = "Hide current planet's info from the ship screen"
websiteUrl = "https://github.com/AndreyMrovol/LethalHideCurrentPlanetInfo"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-WeatherRegistry = "0.1.17"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../HideCurrentPlanetInfo/dist"

[[build.copy]]
source = "../HideCurrentPlanetInfo/bin/Release/netstandard2.1/HideCurrentPlanetInfo.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]